In [ ]:
%load_ext autoreload
%autoreload 2

In [1]:
import os
from pathlib import Path
from itertools import chain

import numpy as np
from PIL import Image
from IPython.display import display

import picograd as pg
from picograd import Variable, Linear, binary_accuracy, AdamW, no_grad, train, sigmoid

In [ ]:
BASE_DIR = Path('datasets/hot_dog')
hot_dog_paths = list((BASE_DIR / 'train/hot_dog').glob('*.jpg'))
not_hot_dog_paths = list((BASE_DIR / 'train/not_hot_dog').glob('*.jpg'))
hot_dog_n = len(hot_dog_paths)
not_hot_dog_n = len(not_hot_dog_paths)
n = hot_dog_n + not_hot_dog_n
hot_dog_n, not_hot_dog_n, n

## Preprocess image

1. Convert RGB to grayscale
2. Center crop to 100px by 100px
3. Convert to fp16 numpy array
4. Normalize to \[0, 1\]

In [ ]:
SIZE = 100

def preprocess_image(path: Path) -> tuple[Image, np.ndarray]:
    img = Image.open(path)
    img = img.convert('L')
    w, h = img.size
    s = min(w, h)
    crop = (w - s) / 2, (h - s) / 2, (w + s) / 2, (h + s) / 2
    img = img.resize((SIZE, SIZE), box=crop)
    return img, np.array(img).astype(np.float16).reshape(-1) / 255.

In [ ]:
im0, _ = preprocess_image(hot_dog_paths[0])
im1, _ = preprocess_image(hot_dog_paths[1])
im2, _ = preprocess_image(hot_dog_paths[2])
im3, _ = preprocess_image(not_hot_dog_paths[0])
im4, _ = preprocess_image(not_hot_dog_paths[1])
im5, _ = preprocess_image(not_hot_dog_paths[2])
display(im0, im1, im2, im3, im4, im5)

In [ ]:
train_y = np.zeros((len(hot_dog_paths) + len(not_hot_dog_paths), 1), dtype=np.float16)
train_y[:len(hot_dog_paths)] = 1

In [ ]:
train_X = np.empty((n, SIZE * SIZE), dtype=np.float16)
for i, path in enumerate(chain(hot_dog_paths, not_hot_dog_paths)):
    _, x = preprocess_image(path)
    train_X[i, ...] = x

# shuffle
p = np.random.permutation(n)
train_X = train_X[p]
train_y = train_y[p]

In [ ]:
class ModelWithoutRegularization(pg.Module):
    def __init__(self):
        self.fc0 = Linear(SIZE * SIZE, 512)
        self.fc1 = Linear(512, 128)
        self.fc2 = Linear(128, 1)

    def __call__(self, x):
        x = self.fc0(x)
        x = pg.relu(x)
        x = self.fc1(x)
        x = pg.relu(x)
        x = self.fc2(x)
        return x

np.random.seed(0)

model0 = ModelWithoutRegularization()
optim0 = AdamW(model0.parameters(), lr=0.01)

In [ ]:
acc = lambda y_pred, y: binary_accuracy(sigmoid(y_pred), y)
pg.train(model0, train_X, train_y, pg.bce_with_logits_loss, acc, optim0,
         batch_size=10,
         max_epochs=10)

In [2]:
import torch
import torch.nn.functional as F

In [3]:
x = np.random.randn(10)
y = np.zeros(10)
y[:5] = 1
x, y

(array([ 0.44492304, -1.79913968,  0.09159841, -1.07627597, -0.75831772,
         0.95323722,  0.89758344,  0.10271596,  0.58031527,  0.90055793]),
 array([1., 1., 1., 1., 1., 0., 0., 0., 0., 0.]))

In [4]:
xt = torch.tensor(x).requires_grad_()
yt = torch.tensor(y)
xt, yt

(tensor([ 0.4449, -1.7991,  0.0916, -1.0763, -0.7583,  0.9532,  0.8976,  0.1027,
          0.5803,  0.9006], dtype=torch.float64, requires_grad=True),
 tensor([1., 1., 1., 1., 1., 0., 0., 0., 0., 0.], dtype=torch.float64))

In [5]:
losst = F.binary_cross_entropy_with_logits(xt, yt)
losst.backward()
losst

tensor(1.1139, dtype=torch.float64,
       grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)

In [6]:
xt.grad

tensor([-0.0391, -0.0858, -0.0477, -0.0746, -0.0681,  0.0722,  0.0710,  0.0526,
         0.0641,  0.0711], dtype=torch.float64)

In [7]:
xp = x.view(Variable)
yp = y.view(Variable)
lossp = pg.bce_with_logits_loss(xp, yp)
lossp.backward()
lossp

Variable([1.11389064])

In [8]:
xp.grad

array([-1.6408736 , -7.04444504, -1.91247151, -3.93373388, -3.13468207,
       -3.59409373, -3.45366652, -2.1081766 , -2.78660161, -3.46097579])